// src/modules/ai/engines/query.engine.js

import mongoose from 'mongoose';
import AI_CONFIG from '../config/ai.config.js';

class QueryEngine {
  constructor() {
    this.models = new Map(); // Cache model references
    this.queryCache = new Map(); // Simple cache for frequent queries
    this.cacheTTL = 5 * 60 * 1000; // 5 minutes
  }
  
  /**
   * Execute a MongoDB query generated by AI
   */
  async executeQuery(querySpec, userPermissions = {}) {
    const startTime = Date.now();
    
    try {
      // Validate query
      this.validateQuery(querySpec);
      
      // Apply permissions
      this.applyPermissions(querySpec, userPermissions);
      
      // Get model
      const Model = this.getModel(querySpec.collection);
      if (!Model) {
        throw new Error(`Unknown collection: ${querySpec.collection}`);
      }
      
      // Check cache for identical queries
      const cacheKey = this.getCacheKey(querySpec);
      const cached = this.getFromCache(cacheKey);
      if (cached) {
        // return cached;
      }
      
      // Execute based on operation type
      let result;
      switch (querySpec.operation) {
        case 'find':
          result = await this.executeFind(Model, querySpec);
          break;
        case 'aggregate':
          result = await this.executeAggregate(Model, querySpec);
          break;
        case 'count':
          result = await this.executeCount(Model, querySpec);
          break;
        case 'distinct':
          result = await this.executeDistinct(Model, querySpec);
          break;
        default:
          throw new Error(`Unsupported operation: ${querySpec.operation}`);
      }
      
      // Cache result
      this.cacheResult(cacheKey, result);
      
      // Log performance
      const duration = Date.now() - startTime;
      console.log(`Query executed in ${duration}ms`, {
        collection: querySpec.collection,
        operation: querySpec.operation,
        resultCount: Array.isArray(result) ? result.length : 1,
      });
      
      return result;
      
    } catch (error) {
      console.error('Query execution error:', error);
      throw new Error(`Query failed: ${error.message}`);
    }
  }
  
  /**
   * Execute find operation
   */
  async executeFind(Model, querySpec) {
    let query = Model.find(querySpec.query || {});
    
    // Apply projection
    if (querySpec.projection) {
      query = query.select(querySpec.projection);
    }
    
    // Apply sort
    if (querySpec.sort) {
      query = query.sort(querySpec.sort);
    }
    
    // Apply limit
    const limit = Math.min(querySpec.limit || AI_CONFIG.limits.defaultRows, AI_CONFIG.limits.maxRows);
    query = query.limit(limit);
    
    // Apply skip
    if (querySpec.skip) {
      query = query.skip(querySpec.skip);
    }
    
    // Apply lean for performance
    query = query.lean();
    
    // Set timeout
    query.maxTimeMS(AI_CONFIG.limits.queryTimeoutMs);
    
    return await query.exec();
  }
  
  /**
   * Execute aggregate operation
   */
  async executeAggregate(Model, querySpec) {
    const pipeline = querySpec.pipeline || [];
    
    // Add limit to pipeline if not present
    const hasLimit = pipeline.some(stage => Object.keys(stage)[0] === '$limit');
    if (!hasLimit) {
      const limit = Math.min(querySpec.limit || AI_CONFIG.limits.defaultRows, AI_CONFIG.limits.maxRows);
      pipeline.push({ $limit: limit });
    }
    
    return await Model.aggregate(pipeline)
    //   .maxTimeMS(AI_CONFIG.limits.queryTimeoutMs)
    //   .exec();
  }
  
  /**
   * Execute count operation
   */
  async executeCount(Model, querySpec) {
    return await Model.countDocuments(querySpec.query || {})
      .maxTimeMS(AI_CONFIG.limits.queryTimeoutMs)
      .exec();
  }
  
  /**
   * Execute distinct operation
   */
  async executeDistinct(Model, querySpec) {
    return await Model.distinct(querySpec.field, querySpec.query || {})
      .maxTimeMS(AI_CONFIG.limits.queryTimeoutMs)
      .exec();
  }
  
  /**
   * Get Mongoose model for collection
   */
  getModel(collectionName) {
    // Check cache
    if (this.models.has(collectionName)) {
      return this.models.get(collectionName);
    }
    
    // Try to get model from mongoose
    let Model;
    try {
      Model = mongoose.model(collectionName);
    } catch (error) {
      // Try singular form
      throw error
      const singular = collectionName.slice(0, -1);
      try {
        Model = mongoose.model(singular);
      } catch (e) {
        throw e
        return null;
      }
    }
    
    this.models.set(collectionName, Model);
    return Model;
  }
  
  /**
   * Validate query for safety
   */
  validateQuery(querySpec) {
    // Check for dangerous operations
    const dangerousOperations = ['$where', '$eval', '$function'];
    const stringified = JSON.stringify(querySpec);
    
    for (const dangerous of dangerousOperations) {
      if (stringified.includes(dangerous)) {
        throw new Error(`Dangerous operation detected: ${dangerous}`);
      }
    }
    
    // Validate limit
    if (querySpec.limit && querySpec.limit > AI_CONFIG.limits.maxRows) {
      throw new Error(`Limit exceeds maximum allowed (${AI_CONFIG.limits.maxRows})`);
    }
    
    return true;
  }
  
  /**
   * Apply user permissions to query
   */
  applyPermissions(querySpec, userPermissions) {
    // If user has department restriction (e.g., HOD)
    if (userPermissions.departmentId) {
      querySpec.query = querySpec.query || {};
      querySpec.query.department = userPermissions.departmentId;
    }
    
    // If user has role restrictions
    if (userPermissions.allowedRoles) {
      querySpec.query = querySpec.query || {};
      querySpec.query.role = { $in: userPermissions.allowedRoles };
    }
    
    return querySpec;
  }
  
  /**
   * Generate cache key from query spec
   */
  getCacheKey(querySpec) {
    return JSON.stringify({
      collection: querySpec.collection,
      operation: querySpec.operation,
      query: querySpec.query,
      projection: querySpec.projection,
      sort: querySpec.sort,
      limit: querySpec.limit,
    });
  }
  
  /**
   * Get from cache
   */
  getFromCache(key) {
    const cached = this.queryCache.get(key);
    if (cached && cached.expires > Date.now()) {
      return cached.data;
    }
    return null;
  }
  
  /**
   * Cache result
   */
  cacheResult(key, data) {
    this.queryCache.set(key, {
      data,
      expires: Date.now() + this.cacheTTL,
    });
  }
  
  /**
   * Clear cache
   */
  clearCache() {
    this.queryCache.clear();
  }
  
  /**
   * Explain query (for debugging)
   */
  async explainQuery(querySpec) {
    const Model = this.getModel(querySpec.collection);
    if (!Model) return null;
    
    let explain;
    switch (querySpec.operation) {
      case 'find':
        explain = await Model.find(querySpec.query || {})
          .explain('executionStats');
        break;
      case 'aggregate':
        explain = await Model.aggregate(querySpec.pipeline || [])
          .explain('executionStats');
        break;
      default:
        return null;
    }
    
    return explain;
  }
}

export default new QueryEngine();